### ISSUE TITLE
Issue with running test in Travis CI

### ISSUE THREAD

**Issue by fozy81** [nodaguti/textlint-rule-no-dead-link#81]
Hi, thanks for this great plugin! I've been trying to add this plugin to a number of tests running on Travis CI. Hopefully, it means we catch any dead links in our documentation when running Travis on new pull requests.

When I run the dead-link plugin in locally it works fine. But when running on Travis I get the following error:

`function reporter(context, options = {}) {`
                                                    
`SyntaxError: Unexpected token =`

see full travis [errors](https://travis-ci.org/fozy81/hoodie/builds/203116209)

Not sure if this is something wrong with plugin or with travis? Sorry my javascript skills are very poor so can't debug any further. Thank you.

**Comment by azu** [comment]
This rule require Node.js >= 6.

You can resolve this issue by specified node version in `.travis.yml`

```
node_js:
  - 6
```

For more details, please see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by fozy81** [comment]
Thanks for the advice. Got it working.
